[book]
chinese_name = "通天之路"
english_name = "The Path of Heaven"
type = "长篇小说"
series.name = "Horus Heresy"
series.order = 36
authors = ["Chris Wraight"]
recommended_reading = [
    "灭绝天使",
    { name = "掌印者", belongto = { name = "无声战争", series = { name = "Horus Heresy", order = 37 } } },
    { name = "恶魔学识", belongto = { name = "无尽的战争", series = { name = "Horus Heresy", order = 33 } } },
    { name = "月之兄弟会", belongto = { name = "泰拉之眼", series = { name = "Horus Heresy", order = 35 } } },
    { name = "忠诚", belongto = { name = "无尽的战争", series = { name = "Horus Heresy", order = 33 } } },
]
faction_keywords = ["白色伤疤", "千子", "帝皇之子", "死亡守卫"]
